travis:
  secure:
    BINSTAR_TOKEN: pIa88FP6BCsS8QLdHy9PxVEqRkrMpmwdzXr6do5iavV2XASoqRRKujsq+34WoNpjGUUES+5kGTCtiWWMl6+CPWR5r8zmfegmlchP/s02mwdevnH1NUJzXvp8Rq3UlhUx1+kRn6fyVVddaIsf8kDawgbZ+icnRHeautO4nP2M4UYDmrebIf5wyB1Oz7FUy5pvU5Qev/et/saKfes1sDoYl65qySADMNgpsoMzD3iuy9hIjv++AX+ZFFxlWn+19JfEfJu5MPreaj0ns2jbNFqWB3IyliWduQwxnbnmreWEULzRNoODrxVh68p/gjSN18Mkaj2V/7/kuqLtuwFvnyuIfaCoBAVimtCHWTeclQ2e24AJ//FVR2MPqMbJYp4Qpnrdtl1qxpepAi2no1kqFghR/uYZd2LfLgyO2dXOl0VdA+rTYIjIv2zRL6p7N2/rgnpif02QTvkzkQrd26AnNq0xF9rBgIvA8te7P3MG2u4M5viqTYz6Up0uiL3fDfM6xrt3PXah/MiFse4a+ujt9wSH2+1bx4fAaYiYdet3NGuJ5bvBhqUMEyjRKmm2xZhC2ewphwDv0W7dzjirTBDUiAorgG5YLmjqSVJdV5WLufw4CJb6p3MfNzU7r5zEeNwUAXt8MFs0+SwZPcUhhpxglky0M8we1coc3EDDC2SM1t6LgUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
